package cli

import (
	"encoding/json"
	"errors"
	"os"
	"os/signal"
	"syscall"

	"github.com/spf13/cobra"
	"github.com/steipete/sonoscli/internal/streamproxy"
)

func newStreamDaemonCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "stream-daemon",
		Short:  "Manage the sonoscli stream proxy daemon",
		Hidden: true,
	}
	cmd.AddCommand(newStreamDaemonServeCmd(flags))
	return cmd
}

func newStreamDaemonServeCmd(flags *rootFlags) *cobra.Command {
	var configPath string
	cmd := &cobra.Command{
		Use:          "serve",
		Short:        "Run a stream proxy server",
		Hidden:       true,
		SilenceUsage: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			if configPath == "" {
				return errors.New("--config is required")
			}
			data, err := os.ReadFile(configPath) //nolint:gosec // hidden daemon command reads the config path generated by play-url.
			if err != nil {
				return err
			}
			var cfg streamproxy.ServerConfig
			if err := json.Unmarshal(data, &cfg); err != nil {
				return err
			}

			ctx, stop := signal.NotifyContext(cmd.Context(), os.Interrupt, syscall.SIGTERM)
			defer stop()
			return streamproxy.NewServer(cfg).Serve(ctx)
		},
	}
	cmd.Flags().StringVar(&configPath, "config", "", "Path to stream proxy config JSON")
	return cmd
}
